---
layout: community
permalink: /community/
---
include::../attributes.adoc[]
= {project-name} - Community

== Getting help

=== Documentation

We have a lot of documentation, be sure to check link:{logisland-site-getting-started}[our getting started] page and all our link:/guides/[guides].  +
Also check out our link:/faq[FAQ] section.

=== Discussions

Stack Overflow::
Ask your questions on https://stackoverflow.com/questions/tagged/logisland[Stack Overflow]. +
After the documentation, probably the best place to look for answers. We actively monitor the https://stackoverflow.com/questions/tagged/logisland[logisland tag].

Mailing list::
You can also ask questions on our mailing list. Join the Google group via email {logisland-mailing-list-subscription-email} or by visiting the Google Groups page {logisland-mailing-list-index}.

Live chat on Zulip::

If you prefer live chat with the developers, we have a {logisland-chat-url}[Zulip chat] where we all hang out.

== An Open Project

{project-name} is an Open Source project licensed under the https://www.apache.org/licenses/LICENSE-2.0[Apache License version 2.0]. First and foremost, it is an open community where contributions, ideas and discussions are done in the open and welcome contributors. Let's join forces in building the future of Java applications.

== Code and issue tracker

The source code is hosted on {logisland-base-url}[GitHub]. If you need to report a bug or request a new feature, look for a similar one on our {logisland-issues-url}[github issues tracker]. If you don’t find any, create a new issue. 


== Contributing

There are a lot of ways to contribute to {project-name} development:

- Writing documentation and quickstarts,
- {logisland-issues-url}[Fixing bugs or even just opening an issue],
- Writing new extensions.

If you are an extension developer or want to contribute to {project-name} development, join our mailing list either:

- by emailing {logisland-mailing-list-subscription-email}
- by visiting the Google Groups page {logisland-mailing-list-index}

Make sure you visit our extensive link:{logisland-site-extension-authors-guide}[extension developer guide].
